### ISSUE TITLE
Code cleaning

### ISSUE THREAD

**Issue by StraToN** [godotengine/escoria#10]
Many scripts included in Escoria contain lines of code that are commented out. We should clean them if they are not needed.

**Comment by lavaduderDev** [comment]
There is also a lot of strange code. For example in telon_music.gd you'll see that it extends 
`"res://demo/objects/item.gd"` Where in the world is that? If it's referring to `"res://globals/item.gd"` Then that's really old code. Is this even need? If so, what for?

**Comment by fleskesvor** [comment]
> There is also a lot of strange code. For example in telon_music.gd you'll see that it extends
"res://demo/objects/item.gd" Where in the world is that? If it's referring to "res://globals/item.gd" Then that's really old code. Is this even need? If so, what for?

`telon_music.gd` is actually not being referenced at all, and may be safely removed. Good catch, @lavaduderDev. 🙂
