### ISSUE TITLE
Fix formatting of esc script reference

### ISSUE THREAD

**Issue by fleskesvor** [godotengine/escoria#103]
The esc script reference in `doc/esc_reference.md` has some formatting issues, which makes it hard to read. These issues include:

- Some esc script examples are not in code blocks
- Esc script descriptions use a larger font than the section headers

There are possibly other issues as well. If possible, we should adopt a markdown syntax which will work well when we eventually publish documentation on Read the Docs.

**Comment by lavaduderDev** [comment]
https://github.com/godotengine/escoria/pull/104

**Comment by fleskesvor** [comment]
@lavaduderDev Exactly like that. 😄Thanks!
