### ISSUE TITLE
Improve support for esc script string comparisons

### ISSUE THREAD

**Issue by fleskesvor** [godotengine/escoria#107]
#102 adds the `eq` operator, which does a string comparison "under the hood", since there's no need to cast arguments to integers. The documentation only mentions the use of this operator for integers, since using it on strings might yield surprising results, specifically because the parser in `parse_flags` splits boolean expressions by looking for the next comma (`,`) and parses the substring from the current position to the next comma as a single expression.

For an expression such as `eq greeting "Hello, World"`, this would be parsed as two expressions, `eq greeting Hello` and `World`, and `World` would be assumed to be a global boolean.

This could be fixed by checking if the next comma is within quotation marks, and if so, skip ahead to the first comma not inside quotation marks. Escaped quotation marks should, if possible, be ignored in this check.

**Comment by dploeger** [comment]
After a rewrite from scratch, Escoria will be re-released in the coming weeks. Because of this, we're closing this issue, because it relates to the old code. If the issue also regards the rewritten code, please feel free to reopen it.

Thanks
