### ISSUE TITLE
Spoken dialogue misaligned

### ISSUE THREAD

**Issue by mjtorn** [godotengine/escoria#112]
Even if the player has a `dialog_pos` node above his head, the actual text ends up drifting pretty much anywhere. So to test this, add a dialog_pos, make sure no fixed position is set, and break into tears.

Do you think positioning would be easier if dialog text was wrapped in `Container`s?

I have no idea how to approach fixing this, everything has failed.

#41 maybe related and #91 touches on the clamping, which I'm pretty sure is ~impossible without containers, like with the action menu.

**Comment by fleskesvor** [comment]
Yeah, I think it probably should be a `Control` node since that's intended for UI elements. I don't know why a `Node2D` is used for regular dialogue when branching dialogue uses a `Control` node.

**Comment by mjtorn** [comment]
Cf. #113

**Comment by mjtorn** [comment]
Done now through #113 and a project setting. It's possible to set the dialog above the player and enforce centering.
