### ISSUE TITLE
Godot 3.0 support?

### ISSUE THREAD

**Issue by ricpelo** [godotengine/escoria#12]
Does Escoria supports Godot 3.0, or are there plans to do so?

Thanks for your great work!

**Comment by StraToN** [comment]
Of course, yes :) . We will try to release it on Asset Store once Godot 3.0 is released.

**Comment by akien-mga** [comment]
Well it probably doesn't support Godot 3.0 out of the box right now, so reopening this issue to keep track of the porting effort. The current *master* should likely be branched off to a *2.x* branch, and we can update master for 3.x.

**Comment by ricpelo** [comment]
Godot 3.0 alpha1 just released. Any progress about this issue?

**Comment by StraToN** [comment]
We need to make more tests since modifications have been made on TSCN format. Issue godot#8465 is still open, we need to have it fixed first.

**Comment by StraToN** [comment]
Job's done! Closing.

**Comment by ricpelo** [comment]
Great!
