### ISSUE TITLE
Walking broken for background_area.gd

### ISSUE THREAD

**Issue by mjtorn** [godotengine/escoria#121]
If the background is a `Sprite` with a texture of the size eg. 3100x1080 and the `background_area.gd` script attached, walking is broken.

Here are my forensics notes, gathered by adding print debugging to the relevant files. Looks like we need a mapping or other type of relationship between the viewport and the underlying sprite/texture/thing is required to move the player to the correct coordinates. Alternatively change the way coordinates work.

I have no idea about how to fix this in practice.

# Using background.gd

## First move a bit down
position	(0, 0)
event pos	(2009.369995, 1044)
var pos	(2009.369995, 1044)
viewport pos	(956, 1044)
get path 	(2013.369995, 895.833984)	(2009.369995, 1044)

## Then toward the right edge
position	(0, 0)
event pos	(2948.370117, 829)
var pos	(2948.370117, 829)
viewport pos	(1899, 829)
get path 	(2009.369995, 1044)	(2948.370117, 829)

# Using background_area.gd

  * Can only move once to the right because downward was moving to the left
  * Note that the event position matches the viewport position

position	(0, 0)
event pos	(1886, 803)
var pos	(1886, 803)
viewport pos	(1886, 803)
get path 	(2013.369995, 895.833984)	(1886, 803)

**Comment by fleskesvor** [comment]
Thanks for the bug report, @mjtorn. I have some ideas on how to fix this, and I will investigate as soon as possible.

**Comment by fleskesvor** [comment]
I made a pull request on your #127 branch (mjtorn/escoria#2), which should fix these issues, no advanced vector math required.

**Comment by fleskesvor** [comment]
Closed by #127
