### ISSUE TITLE
Create inventory toggle button

### ISSUE THREAD

**Issue by fleskesvor** [godotengine/escoria#126]
The inventory should have a button which can be used to open and close the inventory, as mentioned by @StraToN in #123.

It should be possible to configure whether or not to toggle the inventory by clicking the button or having it open the inventory by hovering the mouse. The latter case can also be used to open the inventory with a button without a texture if a developer wants a mouse aware area at the bottom of the screen, which opens the inventory when the cursor enters this area. In that case, the inventory should probably also close when the cursor leaves, unless an item has been selected.

**Comment by lavaduderDev** [comment]
What is this in hud.gd? lines 10-19
```
func inv_toggle():
	#get_node("inventory").toggle()
	pass


func _on_inv_toggle_vis_chaged():
	if (get_node("inv_toggle").is_hidden()):
		get_node("buttons").hide()
	else:
		get_node("buttons").show()
```
Where in the world is the node "buttons" coming from? It's not in the base scene. Was there a node for inventory called buttons at one point? It seems like unneeded code.

**Comment by fleskesvor** [comment]
My guess is it's the remains of some of the same stuff that was removed in #70. It can most likely be safely removed.

**Comment by StraToN** [comment]
This is part of UI design, which has to be developed by gamedev. Escoria will provide API calls to fill the inventory and send according signals when clicking on inventory items, but showing/hiding the inventory is not Escoria's task.
