### ISSUE TITLE
Add stage directions to say command

### ISSUE THREAD

**Issue by mjtorn** [godotengine/escoria#138]
As discussed on IRC, it would be helpful if the `say` syntax supported directions for recording audio, which would end up in the lockit CSV files.

Syntax like `say map_vendor "You can't afford it." [!player_has_money] (Annoyed at Player)`

For a simple project we can just add comments because we have to grep for "say" anyway, but having this in the CSV would help in bigger projects that have to keep track of tons of dialog and the emotions the actor is portraying.

**Comment by mjtorn** [comment]
This issue is about parsing the stage directions and storing them in an internal data structure so lockit.gd can put them to good use. Consider it closed when the directions can be debug-printed off such a structure.

**Comment by fleskesvor** [comment]
Would it be acceptable for your purpose if, instead of creating new esc script syntax, the lockit.gd script would recognise end of line comments and add them to an additional 7th column in the generated CSV file?

**Comment by mjtorn** [comment]
Absolutely, we're using comments for them already!

What we're thinking of, or I am code-wise, for AdventureJam is a simple Python script that grabs the IDs and such comments (where available) into some kind of CSV file, so we can keep track of our recordings. If we get voice acting figured out.

**Comment by fleskesvor** [comment]
I can add this functionality to `lockit.gd` tonight if that saves you the trouble of having to create an additional CSV file with Python and synchronize it with the CSV generated by `lockit.gd`?

**Comment by mjtorn** [comment]
It sure would, thanks a lot!

**Comment by mjtorn** [comment]
Really nice that the code got merged now! Closing, thanks!

**Comment by fleskesvor** [comment]
No problem. :slightly_smiling_face: Sorry that it took so long.
