### ISSUE TITLE
Fix lockit.gd

### ISSUE THREAD

**Issue by mjtorn** [godotengine/escoria#139]
According to https://fr.flossmanuals.net/creating-point-and-click-games-with-escoria/i18n/ translation magic happens with the `lockit.gd` script.

> After it runs, you will get a file called "strings.csv" with all the strings on your esc files, separated by file, and with some context information. You'll also have all the .esc.lockit files generated.

```
$ Godot_v3.0.2-stable_x11.64 -script ../tools/lockit.gd
OpenGL ES 3.0 Renderer: Gallium 0.4 on AMD POLARIS10 (DRM 3.19.0 / 4.14.14-ck1-ryzen, LLVM 3.9.1)
ERROR: load_source_code: Condition ' err ' is true. returned: err
   At: modules/gdscript/gdscript.cpp:792.
ERROR: load: Condition ' err != OK ' is true. returned: RES()
   At: modules/gdscript/gdscript.cpp:1856.
ERROR: _load: Failed loading resource: res://tools/lockit.gd
   At: core/io/resource_loader.cpp:186.
ERROR: start: Failed loading scene: res://tools/lockit.gd
   At: main/main.cpp:1672.
WARNING: cleanup: ObjectDB Instances still exist!
   At: core/object.cpp:1989.
```

It exits with 0.

```
mjt@lechuck:~/src/git_checkouts/escoria (devel *$%<>)$ find . -name strings.csv
mjt@lechuck:~/src/git_checkouts/escoria (devel *$%<>)$ find . -name \*lockit
```

I tested adding some debug prints but nothing really led me to understand wtf is up with this.

#59 should probably be related to fixing this, as well as #138

**Comment by fleskesvor** [comment]
The lockit.gd script is fixed in #140. I will see if there are some other useful features that can be added to it, and then merge it, if no one objects.
