### ISSUE TITLE
Test and document exports

### ISSUE THREAD

**Issue by fleskesvor** [godotengine/escoria#142]
Test that exports are working on

- [x] Linux
- [x] macOS
- [x] Windows

HTML5 exports are know to not be working at the moment.

If possible, test that autosaves are working, and if not, create bug report.

When exporting, *.esc needs to be included explicitly, and that must be documented. Documentation should possibly also include settings/saves paths as documented in http://docs.godotengine.org/en/3.0/tutorials/io/data_paths.html (I think the Mac path is wrong though, re: godotengine/godot#13064.)

**Comment by fleskesvor** [comment]
While testing, I noticed that selecting "No" does not work, neither on "Quit" nor on "New Game" from an already running game. Moreover, the latter seems to leave the game in a very odd state when pressing "Yes" after first having pressed "No.

As far as I can tell, this seems to always have been an issue in 3.0, while the tip of 2.1 works (with Godot 2.x). We might perform a bisect to check when the issue was introduced, but that will require a first pass with bisect to find the first commit which works with Godot v3.0.2 stable.

**Comment by mjtorn** [comment]
I just started setting up the Git stuff for our Jam game, so I can test the material I got from the animators and such, and seeing this kind of an update is nearly panic-worthy.

Do you have some more info on this?

Export the demo scene? Does that mean no menus work?

**Comment by fleskesvor** [comment]
@mjtorn It should be fixed in my latest PR.

**Comment by mjtorn** [comment]
@fleskesvor I thought this was only with exported games, but because I was mistaken, I got to test your PR and it works for me as well.

**Comment by fleskesvor** [comment]
I discovered the bug while testing exports, and assumed so at first, but it turns out that I just hadn't performed the actions required to trigger the bug while testing locally.

Thanks for testing the PR. :slight_smile:

**Comment by fleskesvor** [comment]
I've tested the Linux export now, and it seems to be working without noticeable issues. Things I tested:

- "New game" from the start menu loads the test room as defined by `res://demo/game.esc`
- "Continue" from the start menu loads an autosave if `~/.local/share/godot/app_userdata/Escoria\ Prototype/quick_save.esc` exists. Otherwise the option is grayed out.
- States and globals are correctly added and loaded from `quick_save.esc`
- "Continue" from in-game menu closes the menu
- "New game" from in-game menu makes a prompt appear. Pressing "Yes" restarts the game; pressing "No" closes the prompt (but not the menu).
- "Quit" from menu makes a prompt appear. Pressing "Yes" closes the game; pressing "No" closes the prompt (but not the menu).

Thoughts:

- "New game" from the start menu does not issue a warning about overwriting the autosave. It should, and it would probably be better if the autosave was deleted rather than overwritten, since doing this causes the "Continue" option to not be overwritten, although it clears the globals and states.
- Should pressing "No" on the menu prompts close the menu instead of just closing the prompt?

**Comment by fleskesvor** [comment]
Behaviour is consistent on macOS. Escoria autosave data is written to `~/LibraryApplication\ Support/Godot/app_userdata/Escoria\ Prototype/quick_save.esc` on my Mac.

Games made with Godot 2.1 store their saves under `~.godo/t/app_userdata/[Game\ Name]/quick_save.esc`.

**Comment by fleskesvor** [comment]
Yeah, with #208, which addresses several possible gotchas, I think this can be closed. We can revisit it when we make progress on mobile and web builds.

**Comment by fleskesvor** [comment]
> Yeah, with #208, which addresses several possible gotchas, I think this can be closed. We can revisit it when we make progress on mobile and web builds.

Apparently, I forgot to close this issue. 😞
