### ISSUE TITLE
Black textures after queue_resource on Android

### ISSUE THREAD

**Issue by dwafafiki** [godotengine/escoria#143]
After using the `queue_resource` command, the selected scene loads with black textures on Android devices. Tested on 3 devices (android 5.1 and 7.0), also with a demo project. There were no error messages or warnings on the console.

**Comment by fleskesvor** [comment]
Thanks for the report, @dwafafiki.

I think this might be related to godotengine/godot#17086 and possibly the lack of support for OpenGL ES2, which is still in development for Godot 3. If it's an option, you might try Godot 2.1 with the 2.1 branch of Escoria, but honestly mobile support hasn't been tested much, and if I remember correctly, some of the features used for Dog Mendonça and Deponia on mobile were not merged into the released version of the framework.

We definitely want to support mobile devices though, but it won't be a priority until we've landed a more stable and modular 3.0 version and until support for OpenGL ES2 has been merged into Godot 3.x stable.

**Comment by dploeger** [comment]
After a rewrite from scratch, Escoria will be re-released in the coming weeks. Because of this, we're closing this issue, because it relates to the old code. If the issue also regards the rewritten code, please feel free to reopen it.

Thanks
