### ISSUE TITLE
Improve lockit.gd script

### ISSUE THREAD

**Issue by StraToN** [godotengine/escoria#145]
As @fleskesvor stated in #140:
> There's room for improvement here. Using a shell command to tidy up .lockit files doesn't seem very convenient. Maybe it would be better to support an in-place option like sed does. Ie. overwrite the .esc file but give an optional file extension that will be used to create a backup of the original.

**Comment by fleskesvor** [comment]
We should also write some basic documentation on usage, as well as a nice help text in the CLI, like http://docopt.org/.

**Comment by fleskesvor** [comment]
The script should also use [PoolStringArray.join()](http://docs.godotengine.org/en/3.0/classes/class_poolstringarray.html#class-poolstringarray-join) instead of the custom `join` function implemented in #151.

**Comment by fleskesvor** [comment]
097d288dc501c75b210dda18f510fd183c0b0db3 adds very basic documentation and uses `PoolStringArray.join()`, plus some fixes to write better CSV.

**Comment by StraToN** [comment]
Not used anymore in Escoria 4.
