### ISSUE TITLE
[Feature Request] Ability to slide items

### ISSUE THREAD

**Issue by mjtorn** [godotengine/escoria#176]
In [Iron Sky: A Lunar Adventure](https://gamejolt.com/games/ironsky-lunar-adventure/339236) I have an NPC that gets moved to a disjoint segment of the terrain. I did not have time to implement `slide` and `slide_block` so I tried my best to coordinate animation and teleportation.

---

It could be that an item without separate `directions` animations and using `walk` could lead to the same
effect, but that's not enough.

Say the player walks in front of a big turbine, but the project dosn't have the budget to animate a flailing character, but simply slides him back. Or my case, where an NPC (not a simple item!) experiences low gravity and floats.

The simplest solution would be to `set_state` for the desired animation or sprite and `slide` the object.

This is also future-proof when we finally get npc.gd done.

It would have to remember the scale/z-index of exiting the terrain, if that happens.

**Comment by fleskesvor** [comment]
Couldn't this be solved by having a trigger area in front of the turbine and using the `cut_scene` command to play an animation on the player character, which would have tracks for both the flailing and the changing of position? The last key frame of the flailing track would set the player sprite to one of the idle sprites. The flailing could be optional.

I don't remember if it's possible to have an animation without an initial key frame though. If not, this would result in the player being repositioned to that position at the start of the cut_scene. Alternatively, if we could implement a more general purpose `tween` command for more ad-hoc cutscenes. I'm not sure if there's a good way to pre-configure tweens without knowing their start value up front though.

According to the documentation, `Tween` is "useful for animations with unknown start and end points" (quoted from the 2.1 docs) though, so maybe I'll just have to read up on it:

http://docs.godotengine.org/en/3.0/classes/class_tween.html

I think tween was requested once before too, but I'm not able to find where at the moment.

**Comment by mjtorn** [comment]
As I said above, "doesn't have the budget [...] simply slides him back". We have this case where an NPC is floating upward but we don't want the player to be able to walk there, so the character is `teleport`ed.

Although Spine isn't officially supported, I'm sad to say I don't have the time to put the effort into developing a solution that's very strictly tied to not-Spine :( If a simple esc command won't happen, I'd put the effort into making custom esc commands and implement for my own use :(

**Comment by fleskesvor** [comment]
Yes, but couldn't the low budget version just be `cut_scene` with an animation that just moves and rotates the player node? That should only take a few minutes to implement in an `AnimationPlayer` and can already be triggered with a simple esc command.

Wouldn't the implementation be the same both with and without Spine? Ie. change the position of the player node, plus either trigger a Spine animation or animate the player Sprite.

**Comment by mjtorn** [comment]
Closed since 84f2465
