### ISSUE TITLE
[Feature request] ESC keyword "mumble" or "mutter" or somesuch

### ISSUE THREAD

**Issue by mjtorn** [godotengine/escoria#177]
I had to hack `say` in [Iron Sky: A Lunar Adventure](https://gamejolt.com/games/ironsky-lunar-adventure/339236) to accomplish this. See anything involving the rope in the game.

---

While NPCs are items, they can have a `set_state` and `say` will cause them to speak while being animated.

For the player, no.

Preferably there would be a way to interact with `walk_block` or have a facility for `walk` to take away player control. Then we could have cut-scene-esque situations where the character is maybe told by her boss to clean the toilets and when the dialog tree ends, the joke is that she walks away and complains to herself.

Could also be something like in Broken Age, where Shay is looping an animation (until the player does something) and iirc he comments on the situation every once in a while. Escoria currently would replace that Shay-in-space animation with probably idle.

**Comment by fleskesvor** [comment]
Is the problem that dialog can't be executed at the same time as walking for the player character? I agree that it should be possible.

Shay-in-space might be possible already, but I haven't thought it all the way through. You would animate the cart Shay is sitting in and use trigger areas for making him talk in certain spots and when certain conditions are met. Otherwise he will just be using his idle animations.

**Comment by mjtorn** [comment]
When the player character's walking or otherwise animated, yes.

I mean the part of the game where he's floating in space, not sitting in a cart. IIRC he's kind of rotating.

What would most likely happen is that the animation is rotated, not the character. Instructing the animator to make it so the character is rotated (requiring a new esc command that sets a rotating state), a simple circle would require, what? I think it would boil down to multiple CollisionShapes and very predictable times when he says something, unless some other esc command is introduced like `maybe_say`.

Be that implementation detail what it may, until someone needs it in a game, there should definitely be a way to handle this.

I implemented it like this:

```diff
commit fd1e4ca22a3e891fd95112fdef44f2de27e8d397
Author: Markus Törnqvist <mjt@fadgames.com>
Date:   Wed May 23 07:00:47 2018 +0300

    export var skip_talk_animation for player

    To allow the player to say things while animated
    without replacing it with a speaking animation.

    This is not a general solution.

diff --git a/device/globals/player.gd b/device/globals/player.gd
index f670191..cf0eb42 100644
--- a/device/globals/player.gd
+++ b/device/globals/player.gd
@@ -14,6 +14,7 @@ var path_ofs
 export var speed = 300
 export var v_speed_damp = 1.0
 export(Script) var animations
+export var skip_talk_animation = false
 export(Color) var dialog_color = null
 var last_dir = 0
 var last_scale
@@ -79,6 +80,9 @@ func anim_finished(anim_name):
        _update_terrain()

 func set_speaking(p_speaking):
+       if skip_talk_animation:
+               return
+
        if p_speaking:
                _animation_play({"name": animations.speaks[last_dir]})
                pose_scale = animations.speaks[last_dir + 1]
```

I don't really like the solution. This works pretty much only because our characters are in space suits, so we don't have to care about lip-syncing or even basic mouth movements. In any other game you wold want some kind of animation to happen while the player is walking.

It's hard because something like a walk-speak animation could be implemented, but what if it's something else the player's doing? Having a state like `scrub_toilet` and then wanting a talk animation superimposed on it when `say player player_hate_job:"I hate my job."` happens does not scale that simply.

Could it be so simple that the animations just have to be named in a specific way and `mumble` would use that animation?

Would we start off with having a `mumble` command and figure out how to do more complex animations later?

**Comment by dploeger** [comment]
After a rewrite from scratch, Escoria will be re-released in the coming weeks. Because of this, we're closing this issue, because it relates to the old code. If the issue also regards the rewritten code, please feel free to reopen it.

Thanks
