### ISSUE TITLE
I can not get the Character to move

### ISSUE THREAD

**Issue by lavaduderDev** [godotengine/escoria#18]
I've created a terrain, I've got it all sorted out, WHY ISN'T this character moving. I tried looking at both the flossmanual and test scene. What am I doing wrong?

The link to the issue code.
https://github.com/lavaduderDev/GlitchedupescoriaTerrianissue

**Comment by fleskesvor** [comment]
It's because you have "Ignore Mouse" checked on your background TextureFrame. Uncheck that and it works.

**Comment by lavaduderDev** [comment]
OH ...Hey it works. I feel stupid. THANK YOU!

**Comment by StraToN** [comment]
For this kind of questions, please ask on QA first (don't forget to add an 'escoria' keyword)
https://godotengine.org/qa/
Thanks ! ;)
