### ISSUE TITLE
[Feature request] Automatic interact_angle

### ISSUE THREAD

**Issue by mjtorn** [godotengine/escoria#201]
I spent about an hour on something like this, but couldn't get it to work.

The idea is that -1 would no longer be "whatever" but an indicator that Escoria should calculate the proper angle.

This makes the most sense when you have an NPC that moves to a position where the angle doesn't make sense anymore, like the other edge of the viewport.

Any help would be much appreciated!

PS.
It would also be useful to implement a `turn_toward object1 object2` ESC command, especially so that NPCs can be made to face the player when talking to them, like in the case of walking up from behind.

```diff
diff --git a/device/globals/player.gd b/device/globals/player.gd
index cd67dc3..ec48386 100644
--- a/device/globals/player.gd
+++ b/device/globals/player.gd
@@ -158,8 +158,15 @@ func interact(p_params):
                params_queue = p_params
                walk_to(pos)
        else:
-               if animations.dir_angles.size() > 0 && p_params[0].interact_angle != -1:
-                       last_dir = _get_dir_deg(p_params[0].interact_angle)
+               if animations.dir_angles.size() > 0:
+                       if p_params[0].interact_angle != -1:
+                               last_dir = _get_dir_deg(p_params[0].interact_angle)
+                       else:
+                               # var angle = self.get_angle_to(p_params[0].position)
+                               var angle = p_params[0].get_angle_to(self.position)
+                               printt("INTERACT ANGLE", angle, rad2deg(angle) + 180)
+                               last_dir = _get_dir(angle)
+                               printt("INTERACT DIR", last_dir)
                        animation.play(animations.idles[last_dir])
                        pose_scale = animations.idles[last_dir + 1]
                        _update_terrain()
@@ -174,8 +181,14 @@ func walk_stop(pos):
        task = null
        set_process(false)
        if params_queue != null:
-               if animations.dir_angles.size() > 0 && params_queue[0].interact_angle != -1:
-                       last_dir = _get_dir_deg(params_queue[0].interact_angle)
+               if animations.dir_angles.size() > 0:
+                       if params_queue[0].interact_angle != -1:
+                               last_dir = _get_dir_deg(params_queue[0].interact_angle)
+                       else:
+                               var angle = params_queue[0].get_angle_to(self.position)
+                               printt("WALK_STOP ANGLE", angle, rad2deg(angle) + 180, params_queue[0].name)
+                               last_dir = _get_dir(angle)
+                               printt("WALK_STOP DIR", last_dir)
                        animation.play(animations.idles[last_dir])
                        pose_scale = animations.idles[last_dir + 1]
                        _update_terrain()
@@ -201,7 +214,9 @@ func _get_dir_deg(deg):
        var dir = 0
        var i = 0
        for ang in animations.dir_angles:
+               printt("\tLF", deg, ang)
                if deg <= ang:
+                       printt("\t\tFOUND", i)
                        dir = i
                        break
                i+=2
```

**Comment by StraToN** [comment]
I agree on the idea of a `turn_towards` ESC command. IIRC, SCUMM does have such functionality.

ESC is supposed to be used by scripters, not by programmers, so one shouldn't have to deal with orientation angles of characters or items whatsoever. Any functionality that drives the game execution in a scenaristic way instead of technical way, is good to have (ie. "turn player so he faces NPC1" is better than "get NPC1 position, determine necessary rotation so player faces this position, and rotate player of this angle".

**Comment by mjtorn** [comment]
The angle code has changed a bit since the above diff, and I should give this another shot at some point (unless someone beats me to it!) but I don't think we have any actual use case for automatic angle calculation.

In A Lunar Adventure the female NPC moves from her initial position and that causes the `interact_angle` to look weird. It would be best to always calculate automatically.

So let's see when this thing moves forward, but glad to hear we agree on this! :)

**Comment by mjtorn** [comment]
This has been done since around 81e87cd0 - closing
