### ISSUE TITLE
Investigate possibility of unifying functionality in telon

### ISSUE THREAD

**Issue by fleskesvor** [godotengine/escoria#207]
In light of #203, we should take a closer look at telon to see if there are good reasons for `catch_input`+`release_input` to remain separate from `disable_input`+`enable_input` and weigh the pros and cons, both from a design and implementation perspective, eg. "does this feel like good design?", "does it make maintainability harder/easier?"

`telon.gd` is also a prime candidate for code cleaning, but that is tracked by #10, and need not be handled by this issue, which is possibly a no-op.

**Comment by StraToN** [comment]
Not relevant in Escoria rewrite anymore.
