### ISSUE TITLE
Would a z-index map be valuable?

### ISSUE THREAD

**Issue by mjtorn** [godotengine/escoria#222]
As #209 drags on to frustrating lengths, I can't help but think if there could be a better separation of concerns between scaling and z-indexing. But merging #209 first ;)

The color red (gradient to alpha, probably) could be used in the same way as light and scale maps but to set the player's and items' (~= NPCs') z-indexes.

I see some problems with this, though. The main hardship with this in that those maps are fscking hard to get right. Even then the values need to be attenuated in the editor. Something like "I want this guy to walk in front of that item" should be simpler.

So you'd be stuck with making the gradient, which is hard, and then setting the limit values (what value of z-index is the purest red?) and hoping the gradient still makes sense.

**Comment by fleskesvor** [comment]
In addition to being hard to maintain, a z-index map also wouldn't solve the issue of overlapping items. As far as I can tell, #258 solves the same problem, but in a way that is much easier to maintain. Are you OK with closing this issue, @mjtorn?

**Comment by mjtorn** [comment]
Sure, go ahead and close it. I'll get back to this matter if I
ever have to ;)
