### ISSUE TITLE
Once Godot can calculate the width of a label's content, clamp tooltips based on it

### ISSUE THREAD

**Issue by mjtorn** [godotengine/escoria#227]
Currently there's a fixed width for tooltips, which looks problematic. This will need attention when possible.

**Comment by StraToN** [comment]
To be checked and fixed in Escoria Rewrite.

**Comment by dploeger** [comment]
After a rewrite from scratch, Escoria will be re-released in the coming weeks. Because of this, we're closing this issue, because it relates to the old code. If the issue also regards the rewritten code, please feel free to reopen it.

Thanks
