### ISSUE TITLE
Some kind of menu item type

### ISSUE THREAD

**Issue by mjtorn** [godotengine/escoria#230]
Since commit 2450057 I started thinking that the menu code is a bit of a mess. It sort of handles only `Label` but it also sort of handles only `TextureRect` (which is the more versatile choice!).

Personally I haven't tried localizing this stuff yet, but I'm sure some kind of language representation in the scene tree could be useful, unless we go by filesystem hierarchy, but that kind of loading makes it harder to preview stuff in the editor. Think about how hard dialog choices are to align and debug!

Then someone might want sounds and animations when hovering or clicking. There is a stub `button_clicked()` function, so someone has thought about this.

------

I believe having a `menu_item.gd` script would make discovery and tree-layout validation easier.

What do you guys think about the idea?

What should the layout look like?

I think the lightest solution for audio and animation would be to have `menu_item.gd` have some `export var` magick, and a central `AnimationPlayer` would look at something like the `labels` structure as a registry for what to do on different events.

I haven't had time to think about localization at all, really, but I suppose the buttons `new_game` etc should probably live under a node named like `lang_en` or `lang_fi`. The visibility of these `lang_*` nodes would be toggled when the language changes.

Should we be able to affect the background in a similar way? I think we could ask developers to add only non-localized elements in the background proper and mess around with children of `lang_*` for decoration elements.

**Comment by StraToN** [comment]
This is a good idea, it's just integrating a Godot feature into Escoria.
My only fear is that, doing this may limit users possibilities while using Godot directly would be enough already.

**Comment by StraToN** [comment]
Not relevant in Escoria rewrite, as all UI (including main menu, pause menu and so on) is the gamedev's burden. Escoria does not interfer with it, the gamedev just makes call to Escoria API when required.
