### ISSUE TITLE
Change default action based on game state

### ISSUE THREAD

**Issue by mjtorn** [godotengine/escoria#240]
I received an enhancement idea that I first doubted a bit, for making thing hard to predict, but on second thought it kind of makes sense.

Here's the synthetic version of the example. You double-click at a motorbike, player says "I need the keys".

You get the keys, double-click, and there's a cutscene of the player driving away (and with a `gt` check or something don't do the cutscene too many times ;).

@StraToN @fleskesvor do you think this has a place in Escoria?

It would affect the save games; the default action will be tracked and set etc.

Can't promise anyone when I'd get around to it and it would be nice if it wasn't me doing it ;P

**Comment by StraToN** [comment]
I don't think this is required. 
In the specific case you described, the same event ":use" is called in both case when you double click the motorbike, whether the player has the keys or not. You can do whatever you want with a simple test in the event.

in motorbike.esc:
```
:use 
> [!i/motorbike_keys]
say player "I need the keys." 
stop
> [i/motorbike_keys]
# play cutscene
```
