### ISSUE TITLE
Request menu during dialog

### ISSUE THREAD

**Issue by mjtorn** [godotengine/escoria#241]
If someone's speaking or the dialog choice box is open, in-game menu can't be accessed.

Personally I can't prioritize this too high, but it makes sense that the menu should always be accessible.

**Comment by StraToN** [comment]
Agreed. Will take this into account in the rewrite.

**Comment by dploeger** [comment]
After a rewrite from scratch, Escoria will be re-released in the coming weeks. Because of this, we're closing this issue, because it relates to the old code. If the issue also regards the rewritten code, please feel free to reopen it.

Thanks
