### ISSUE TITLE
Conditional builds/debug exports of some kind

### ISSUE THREAD

**Issue by mjtorn** [godotengine/escoria#242]
I don't know if Godot does this to any extent, but it would be super-nice to have debug exports of games.

A big use case would be to overload the escape key action to skip a cutscene which would not be skippable in the final game.

**Comment by fleskesvor** [comment]
I agree, and it should be doable by exporting the game with `--export-debug` ([docs](https://docs.godotengine.org/en/stable/getting_started/workflow/export/exporting_projects.html#exporting-from-the-command-line)), and using `OS.is_debug_build()` ([docs](https://docs.godotengine.org/en/stable/classes/class_os.html#class-os-method-is-debug-build)) for conditional behavior.

**Comment by dploeger** [comment]
After a rewrite from scratch, Escoria will be re-released in the coming weeks. Because of this, we're closing this issue, because it relates to the old code. If the issue also regards the rewritten code, please feel free to reopen it.

Thanks
