### ISSUE TITLE
Parser Error: Cannot assign a new value to a constant

### ISSUE THREAD

**Issue by neosin** [godotengine/escoria#264]
Just dowloaded this and extracted to a folder.
Went into "escoria-master\device" and loaded project.godot with godot 3.1 latest
Then I clicked the play button to test the demo.
It was compiling and then gives the error "Parser Error: Cannot assign a new value to a constant" 
0 - res://globals/vm_level.gd:407
fun set_vm(p_vm):
vm=p_vm;

I am new to godot and have no idea how to get this demo to run.
any help would be appreciated
thank you

**Comment by mjtorn** [comment]
@neosin excellent timing ;) The 3.1 work is coming along pretty neat; you can find the work at https://github.com/godotengine/escoria/pull/263

It's not going to be merged until @StraToN says so, but feel free to try out my branch. You can also test the 3.1 branch in the repo as it is, but it was most useful as a starting point for further work and might not be complete.

I played through our in-progress game [Iron Sky: A Lunar Adventure Deluxe](https://ironsky.game/) (which is not mentioned in the link until we have our new site up) more or less with the PR code base. Admittedly there were some issues during it, which I fixed and didn't start from scratch every time, but things really seem to work.

Disclaimer: I did not have time to test the demo rooms, really. Too busy with actual games and @StraToN has ownership of the demo rooms. No reason they shouldn't work despite that!

Please let us, or me, know what you get with my branch! Or if you prefer to wait a while, let us know if things work for you after the big merge :)

**Comment by mjtorn** [comment]
@neosin the master branch has now been updated with 3.1 code. You should be able to get started with that, and if you want to test #265 before it's merged, that'd be sweet to.

Closing - don't hesitate to reopen if required!
