### ISSUE TITLE
Re-architecture vm/main/game

### ISSUE THREAD

**Issue by mjtorn** [godotengine/escoria#266]
# Problem
Changing scenes involves a lot of work. All the game/hud stuff is reloaded, which causes glitches for a default-visible inventory, for example, when it should be hidden during changes. It's also generally excessive to do that work when things this static should be more like singletons.

# Proposal

Change things around so that `game` is defined in `ProjectSettings` as `default_game_layout`. It should not have any references to anything in the scene, like `camera`.

Move `camera` to the scene. It could be instantiated so we don't have to care about attaching the script and adding the `Tween` child to it.

This has the benefits:
  * Not having the camera show up in coordinates (0, 0) in the editor.
  * Having the drag margins configurable in the correct place - the camera instead of the game layout

Initialize `vm` before `main` if required. During my testing I found that this set some things up more correctly, but might have been a false lead in experimentation. Or a random occurrence if the AutoLoads are not guaranteed to be ordered.

# Unresolved questions

Experimentation in this caused everything in the game to break down badly wrt setting things up. Because Godot complains that `add_child()` fails as the node is busy setting up its children, and suggests `call_deferred()`, the children reliant on `game` will fail to set up. Adding a custom event to them seemed to circumvent some issues, with the effect that the game had elements in the wrong places on-screen.

How do we deal with rooms that have a different layout? I think it should be possible to have a `game` node, which if present, overrides the default one. Signal handlers are, however, connected to the default one, so how do we reconnect them? Or does it Just Work(tm) because the custom `game` node takes care of it when entering the tree?

When and how do we free the default `game`?

If we have to yield on a custom signal, are we really sure it doesn't cause side-effects in setting up all the items and background and such if a custom `game` enters the tree late? It should be ok.

**Comment by StraToN** [comment]
Not relevant anymore for Escoria rewrite. Still keeping this in archived label though.
