### ISSUE TITLE
Escoria 3.0 : Loading issues and crash of demo game with Godot 3.0.x

### ISSUE THREAD

**Issue by jeancallisti** [godotengine/escoria#270]
Scenario : 
- Windows 10 (64 bits)
- Download the current escoria 3.0 branch (commit 7f43073  - 22nd June 2019)
- Download Godot 3.0.6
- Load the Escoria demo game into Godot (Scan then Edit)
- **With Godot 3.0.6** : in the console, several errors like " _ERROR: load_interactive: Condition ' err != OK ' is true. returned: Ref<ResourceInteractiveLoader>()            **At: core/io/resource_format_binary.cpp:997_** "
(Please note that this loading error does not happen with Godot 3.0)

- Run the demo game without changing anything.
- In the adventure scene, click a few times to move the character

- Quickly you get a game crash with error: 
  - In the script: Error at player.gd line 365 "Invalid get index 'scale' (on base: 'null instance')"
  - In the console: "Node not found: Collision. At scene/main/node.cpp:1524"
 This runtime crash happens with **any Godot 3.0.x** (tested with 3.0 and 3.0.6)

**Comment by jeancallisti** [comment]
?

**Comment by Vikram1323** [comment]
I found a way to fix some things.
Open player.tscn 
* create walk_left and idle_left with flip_h checked then
* open player_anims.gd and change
* "walk_right", -1 to "walk_left", 1 and
* "idle_right", -1 to "idle_right", 1

By doing this instead using mirror of walk_right and idle_right we are using walk_left and idle_left.
Any question feel free to ask.

**Comment by Beuc** [comment]
FYI, while Escoria 3.x is in progress, Escoria 2 was ported to Godot 3.2 (branch esc2-godot3.2) and featured in the godot assets lib. The Escoria in Daïza was updated too.

**Comment by Vikram1323** [comment]
@Beuc What do you think is more reliable branch of escoria with Godot 3.2.x. Can you please tell what do you think about using Escoria 3.x in its present state with Godot 3.2.x. Thanks for update.

**Comment by ArturM** [comment]
I'm using Escoria 3.x from master (with a few minor changes) with Gotot 3.2 on daily basis. 
Couldn't make my game on Escoria 2 - so I'm using Escoria 3.x :)

**Comment by Vikram1323** [comment]
@ArturM I saw your fork of Escoria. That means I should use your 3.2-WIP branch. Am I correct. Thanks.

**Comment by Beuc** [comment]
Hi,

- Escoria 2.0 is stable and won't change significantly; that means you can upgrade it (for fixes and/or new Godot version) and it'll keep working; however don't expect new features

- Escoria 3.x is under development and may change; if it works for you right now, you can use it, but if you upgrade Escoria 3.x to get new fixes/features, you may have to make changes to your game

**Comment by Vikram1323** [comment]
@Beuc Trade-off between .... and .... Waiting for ... and .... never ending part of life. Thanks for saving my time :)
