### ISSUE TITLE
Player animated by Skeleton2D

### ISSUE THREAD

**Issue by ArturM** [godotengine/escoria#278]
I did something like that:

![anatol_20200215](https://user-images.githubusercontent.com/322591/74773540-58fe8700-5292-11ea-85be-d6d6e637472d.gif)

Player is animated by 'cutout animation' driven by Skeleton2D.
One Skeleton2D and 'polygons' for side walk and another Skeleton2D and 'polygons' for up/down.
Skeletons and polygons are enabled/disabled by animations i.e. 'walk left' disables Skeleton2D_front and polygons_front and enables Skeleton2D_side and polygons_side.   

There's my screen:

![Zrzut ekranu z 2020-02-18 21-07-27](https://user-images.githubusercontent.com/322591/74773928-1c7f5b00-5293-11ea-9156-a11a7934ed64.png)

To make flipping left-right work I've modified code in player.gd - from line 363 to 377 on screen and below:

`

      # Do not flip the entire player character, because that would conflict
      # with shadows that expect to be siblings of $"sprite"

	if pose_scale == -1 and $"sprite".scale.x > 0:
		$"sprite".scale.x *= pose_scale
		$"collision".scale.x *= pose_scale
		if has_node("polygons_side"):
			$"polygons_side".scale.x *= pose_scale
		if has_node("Skeleton2D_side"):
			$"Skeleton2D_side".scale.x *= pose_scale		
	elif pose_scale == 1 and $"sprite".scale.x < 0:
		$"sprite".scale.x *= -1
		$"collision".scale.x *= -1
		if has_node("polygons_side"):
			$"polygons_side".scale.x *= -1
		if has_node("Skeleton2D_side"):			
			$"Skeleton2D_side".scale.x *= -1`

Works, but this adds another hardcoded nodes to player - how it should be done?

**Comment by fleskesvor** [comment]
The best way to solve this, is probably to make a base player script which extends `Node2D` (or a closer common ancestor) which contains the common variables and functions of eg `player_kinematic` and `player_skeleton`, and implement the differences in extending scripts. You'll find examples of this in eg. `item.gd` and `trigger.gd`, which both extends `interactive.gd`.

**Comment by dploeger** [comment]
After a rewrite from scratch, Escoria will be re-released in the coming weeks. Because of this, we're closing this issue, because it relates to the old code. If the issue also regards the rewritten code, please feel free to reopen it.

Thanks
