### ISSUE TITLE
New ESC command proposal - rand_global

### ISSUE THREAD

**Issue by ArturM** [godotengine/escoria#279]
We have **inc_global** and **dec_global**.
What about **rand_global**?

* `rand_global name value` - changes value of global to random value from 0 to value-1

Will be very handy for randomize NPC quotes or to add some randomness to puzzles - like numbers to open clown's safe in Thimbleweed Park - every time you play game numbers are slightly different.

**Comment by fleskesvor** [comment]
Yes, this sounds like a useful addition. :+1:

**Comment by ArturM** [comment]
I've added this to my game in February :)

`Added rand_global ESC command

3 files changed, 10 insertions(+)
globals/esc_compile.gd | 1 +
globals/global_vm.gd   | 5 +++++
globals/vm_level.gd    | 4 ++++

modified   globals/esc_compile.gd
@@ -13,6 +13,7 @@ var commands = {
 	"dec_global": { "min_args": 2, "types": [TYPE_STRING, TYPE_INT] },
 	"inc_global": { "min_args": 2, "types": [TYPE_STRING, TYPE_INT] },
 	"set_globals": { "min_args": 2, "types": [TYPE_STRING, TYPE_BOOL] },
+	"rand_global" : {"min_args" : 2, "types": [TYPE_STRING, TYPE_INT] },
 	"accept_input": { "min_args": 1, "types": [TYPE_STRING] },
 	"debug": { "min_args": 1 },
 	"anim": { "min_args": 2, "types": [TYPE_STRING, TYPE_STRING, TYPE_BOOL, TYPE_BOOL, TYPE_BOOL] },
modified   globals/global_vm.gd
@@ -697,6 +697,11 @@ func set_globals(pat, val):
 			globals[key] = val
 			emit_signal("global_changed", key)
 
+func rand_global(name, val):
+	randomize()
+	globals[name] = randi() % val + 1
+	emit_signal("global_changed", name)
+			
 func set_accept_input(p_accept_input):
 	if p_accept_input == acceptable_inputs.INPUT_NONE || p_accept_input == acceptable_inputs.INPUT_SKIP:
 		vm.set_global("save_disabled", "true")
modified   globals/vm_level.gd
@@ -62,6 +62,10 @@ func inc_global(params):
 	vm.inc_global(params[0], params[1])
 	return vm.state_return
 
+func rand_global(params):
+	vm.rand_global(params[0], params[1])
+	return vm.state_return
+
 func debug(params):
 	for p in params:
 		printt(p)
`

**Comment by fleskesvor** [comment]
Nice. 😄 That can probably be merged as-is, if you want to create a PR? It should be added to the [command list in the docs](https://github.com/godotengine/escoria/blob/master/docs/esc_reference.md#command-list) too, if so.

**Comment by StraToN** [comment]
Will be part of the new Escoria rewrite arriving soon. Thanks!
