### ISSUE TITLE
Seting and checking global flags outside of .esc files with GDScript

### ISSUE THREAD

**Issue by Kubees** [godotengine/escoria#28]
**Hello!**

   First of all, I want to say, that _Escoria_ really is an awesome tool for creating point-and-click games and THIS is something, that I was really looking for, mainly for its easy to use script writing and utilizing _Godot's_ cool animation system. I am still learning, how to use _GDScript_, but this made it far easier to achieve something. Thank you, guys, thank you very, very much!

   And now to my question. In _Escoria's_ script, I can define and check for global flags. Is there any way, how to set, call or check them in _GDScript_? Can they actually communicate with each other? For instance, imagine a situtation, when I, as a player, click on vending machine, player goes to it and now, it will change scene to sort of minigame, where nothing would be driven by _Escoria_ script. If player wins this minigame, scripted in _GDScript_, if he kills all aliens, is there any way to let _Escoria_ script know, that he did it? To set a global flag outside of _Escoria_, in _GDScript_, which actually can be recognised while using .esc files?

   I was wondering about this, because _Escoria's_ use is pretty straight forward and it kinds of define, how your game should look like. If I want to do something more complex, for instance when I succesfully build a wall without hole from a tetris blocks (minigame, which _Escoria_ can't handle), I would really like to return changed condition back to _Escoria_. After finding a solution, I think, you can do almost anything.

   I found script, which creates the boolean global flag, but I am still wondering, how to call it or set it inside of _GDScript_. Oh, those hard times being newbie. Sorry guys and thank you for all answers!

**Comment by fleskesvor** [comment]
Yes, you can do that by doing something like this from a GDScript file

    var vm = get_tree().get_root().get_node("/root/vm")
    vm.set_global("won_tetris", true)

`vm` is one of the pre-defined AutoLoads in "Project Settings", so I think you can just access it as a singleton if you enable that in the settings. I'm not sure if that might cause other issues though, so probably best to just use this construct for now, as it's what all current examples use.

You should think of Escoria more as an aid than a fixed framework that you're limited by. There's nothing wrong with utilizing everything Godot has to offer in your game, even though it's not supported by Escoria.

As an example, you could take a look at [The Farrier](https://github.com/Cheeseness/the-farrier) (just keep in mind that it's rushed, and not exactly an example of best practices), which I collaborated on as part of Adventure Jam 2017. It's built on Escoria, but there's a lot of custom stuff built around the framework too. As you can see in `esc_compile.gd` and `vm_level.gd`, it's also very easy to add custom functions supported by Escoria scripts, such as `set_tool` in our case.

As for checking for globals, that can be easily done by connecting a function to the "global_changed" signal emitted by the previously declared `vm`, like:

    vm.connect("global_changed", self, "my_custom_listener")

and then checking if the name of the global passed to that function as an argument is one you're interested in.

**Comment by StraToN** [comment]
It seems the answer provided helped. I close the issue, feel free to re-open if you need :)
