### ISSUE TITLE
Multiple talking animations using states/2 animationplayers

### ISSUE THREAD

**Issue by 4remy** [godotengine/escoria#280]
This is my first github post, I apologise if this is in the wrong place.

I am using Godot 3.1.1 with Escoria 3.1, and am testing multiple talk animations using states on an item ('old_man'). I found Punto and Fleskevor's responses helpful when this topic was raised in the past ([here](https://github.com/godotengine/escoria/issues/30) and [here)](https://github.com/godotengine/escoria/pull/147) 

The output is telling me that I am correctly changing states, and a non-talk animated state ('sad'), within the primary animation player is being called correctly.

My animation players are named 'animation' and 'angry' respectively, shown in the screenshot. Changing the name of the first one (i.e. to 'default') breaks it. 
![Screenshot 2020-02-25 at 3 25 11 PM](https://user-images.githubusercontent.com/23172853/75297076-c4d97600-57e3-11ea-81c4-d0ad18565e29.png)

On the section that says
```
set_state old_man angry
say old_man "VERY ANGRY.."
```
I would expect it to show the second talk animation within the 'angry' animation player, but it still shows the first talk animation, within 'animation'.

I'm sure I'm missing something basic here to connect them, but I've spent days trying to fix it.

![Screenshot 2020-02-25 at 3 36 09 PM](https://user-images.githubusercontent.com/23172853/75297388-98722980-57e4-11ea-81d3-06e242a452bb.png)
This is inside the AnimatedSprite - I think my mistake could be to do with the name of the 'default' animation, or the way that the 'angry' state is called in the old_man's .esc file, but I'm not sure what to change it to.

**Comment by ArturM** [comment]
Hi,

**set_state** from .esc file selects AnimationPlayer used by old_man.
**set_state old_man angry** selects AnimationPlayer **angry**.

Now **say** from .esc file plays animation selected in old_man's Inspector panel in field "Talk Animation" - by default there is 'talk'

So in Animation Player **angry** change name of animation from **angry** to **talk**
Hope this helps :)

**Comment by 4remy** [comment]
Hi Artur, thank you for your reply, I really appreciate it. Inside the AnimationPlayer **angry** the animation was already labelled **talk** - pretty confusing! 

A friend managed to help me with a work-around - this is based on Punto's advice in a previous thread. The solution means that multiple talking animations are stored in the same player, now called **talk** and **angry_talk**. They made two additions to the code in the item.gd script - pasting the relevant bits below.

![Screenshot 2020-02-26 at 1 34 53 PM](https://user-images.githubusercontent.com/23172853/75390335-f7937500-589c-11ea-8eeb-8b569714af6b.png)


`#warning-ignore:unused_class_variable
export(int, -1, 360) var interact_angle = -1
#warning-ignore:unused_class_variable
export(Color) var dialog_color = null
export(Script) var animations
export var talk_animation = "talk"
export var angry_talk_animation = "angry_talk"
export var placeholders = {}
export var dynamic_z_index = true
export var speed = 300
export var scale_on_map = false
export var light_on_map = false setget set_light_on_map
export var is_interactive = true


func set_speaking(p_speaking):
	printt("item set speaking! ", global_id, p_speaking, state)
	#print_stack()
	if !animation:
		return
	if talk_animation == "":
		return
	if p_speaking:
		if animation.has_animation(talk_animation):
			if (state == "angry"):
				animation.play(angry_talk_animation)
				animation.seek(0,true)
			elif (state == "default"):
				animation.play(talk_animation)
				animation.seek(0, true)`

I'll close this issue now, although I'm still curious about my mistake in the original method. Changing state always only changed to other animations within the same player, and I never worked out how to 'move up a level' to changing players themselves.
