### ISSUE TITLE
Tried my hand at the panda scene, but base scene buttons don't work

### ISSUE THREAD

**Issue by matthewedogawa** [godotengine/escoria#286]
I followed the instructions in the guide, but for some reason my buttons aren't working.  I get to the part where they have me enter text for the old man panda, but for some reason, none of my buttons including the talk button seem to activate after I copy the base scene into the intro game folder.  I swear I'm just opening the scene like they said in this tutorial (https://fr.flossmanuals.net/creating-point-and-click-games-with-escoria/creat-actions/), but it doesn't seem to work.

**Comment by Vikram1323** [comment]
First you have to click the button then item with item.gd script attached to it.
If it is not working then 
- check Global Id of item in inspector
- check Event Path property in inspector

Items need
- item.gd script
- clickable area or click mask or button texture etc depending on version of escoria
- Global Id in inspector
- Event Path in inspector (esc script)

**Comment by fleskesvor** [comment]
I'm closing this issue, since an answer has been provided (thanks @Vikram1323 :hugs:). If the provided answer doesn't answer your question, @matthewedogawa, feel free to re-open it, and I'll take another look.
