### ISSUE TITLE
video overlay implementation

### ISSUE THREAD

**Issue by JstCruzn86** [godotengine/escoria#287]
Greetings. Please consider implementation of video overlays such as on top of pre-rendered frames to allow for animations like those in Myst/Riven.

**Comment by fleskesvor** [comment]
Hi. Could you please provide an example of what you mean, and clarify how you think it should tie in with the Escoria framework, so that I might have a better understanding of what you're asking for.

**Comment by StraToN** [comment]
Good idea. I'm keeping this for Escoria rewrite. However it will probably not be done very soon. 
Could you please provide a sample video I can use for implementing this feature? Thanks in advance.

**Comment by dploeger** [comment]
After a rewrite from scratch, Escoria will be re-released in the coming weeks. Because of this, we're closing this issue, because it relates to the old code. If the issue also regards the rewritten code, please feel free to reopen it.

Thanks

**Comment by JstCruzn86** [comment]
Sorry for the late reply. I've since used a different framework for my project. To best describe the scenario: A static image or backdrop, but a portion of it overlayed with video for fluid animation, such as a door opening, switch toggling, water flowing, etc.

**Comment by dploeger** [comment]
Thanks for the reply, @JstCruzn86. This is already possible in different ways in Godot Core:

* Using an AnimatedSprite and playing its animation
* Using a Sprite or TextureRect with an AnimatedTexture
* Using a Sprite or TextureRect together with AnimationPlayer2D to control the animation

You can even put it in a CanvasLayer with a higher layer to make it appear in front of the characters.
