### ISSUE TITLE
dialog_default does not handle finishing animated dialog correctly

### ISSUE THREAD

**Issue by Lovewyrm** [godotengine/escoria#290]
I'm on commit 74edead092f05afdf38339376d7f120fbadeb18d

In the original version _queue_free() is not called if one has an animation.
The text file attached is a patch that fixes it, but I don't know if it's a good fix, since I have very little experience with the framework.

[fix_dialog_finish.txt](https://github.com/godotengine/escoria/files/5429377/fix_dialog_finish.txt)

**Comment by StraToN** [comment]
Not relevant anymore with Escoria rewrite.
