### ISSUE TITLE
speech dialog ends prematurely if typewriter text speed is low and there is no speech audio

### ISSUE THREAD

**Issue by Lovewyrm** [godotengine/escoria#291]
I'm on 74edead092f05afdf38339376d7f120fbadeb18d

It hits "print_debug("finishing text")", in the escoria Demo, anyway. 
Maybe it should also check if the text is done? Because if you set the text speed to very low, and there is no speech, the dialog will close after the time specified in timeout settings .

```
	if elapsed > text_timeout_seconds and (!speech_player or !speech_player.is_playing()):
		print_debug("finishing text")
		finish()
		return

	if vm.settings.skip_dialog && speech_stream != null && !speech_player.is_playing() && text_done:
		finish()
		return
```

**Comment by Lovewyrm** [comment]
Checking if the text is done too fixes it.
But as I pointed out in the other issue I made, I am not experienced with godot or escoria, so ...yeah.

**Comment by StraToN** [comment]
To be retested in Escoria rewrite.

**Comment by dploeger** [comment]
After a rewrite from scratch, Escoria will be re-released in the coming weeks. Because of this, we're closing this issue, because it relates to the old code. If the issue also regards the rewritten code, please feel free to reopen it.

Thanks
