### ISSUE TITLE
HUD stays invisible after dialog

### ISSUE THREAD

**Issue by HarleyDavidson86** [godotengine/escoria#296]
When I start a dialogue with an item the HUD with tooltips stays invisible forever.
I also cannot open the inventory with TAB then.

Current workaround: set_hud_visible true in the last line.
```
:talk
say p1 "Hi there"
?
	- "Option 1"
		say player "Message 1"
		say p1 "Message 2"
set_hud_visible true
```

After a dialogue the hud should be visible again?
I checked this by output the value in hud.gd, line 40 (function set_visible). At the beginning, visible-value is set to false but never back to true.

**Comment by ArturM** [comment]
https://github.com/godotengine/escoria/blob/master/docs/esc_reference.md
section 'Dialogs':

'Use "!" to signify the dialog is over and the HUD may be restored.'

Just add '!' in new line after: say p1 "Message 2"
