### ISSUE TITLE
Resolution

### ISSUE THREAD

**Issue by Zavy86** [godotengine/escoria#297]
Hi, what is the best way to change the game resolution?
I want to build a pixel art game and I would like to limit the display to 480x270.
It's possibile?

**Comment by StraToN** [comment]
The game resolution management is handled by Godot directly. Escoria does not interfer with it.
You can find precise information about what you need in the official documentation: https://docs.godotengine.org/en/stable/tutorials/viewports/multiple_resolutions.html

IINM, for a pixel art game you may want to set Stretch Mode as "Viewport", and Stretch Aspect to "Keep" or "Keep Width".
