### ISSUE TITLE
Make a full game 

### ISSUE THREAD

**Issue by punto-** [godotengine/escoria#298]
I'd like to make a full Escoria game, to test the current codebase on a modern version of the engine. Where can we recruit people for this ? (Discord, reddit ?) Artists, game designers, dialog/story writers. Programmers too, but as support only, or to write custom code for minigame, etc. Could we make something production quality, that can ship on Steam, consoles, etc ? Would we need to fund it ?

**Comment by StraToN** [comment]
Hello,

This place is for issues, bugs or feature requests. For questions regarding your own projects and finding people to contribute your project, you may ask on the various community channels offered by Godot community which you can find here: https://godotengine.org/community

Question about console ports have [an answer in the official documentation](https://docs.godotengine.org/en/latest/tutorials/platform/consoles.html).
