### ISSUE TITLE
Missing assets for escoria book

### ISSUE THREAD

**Issue by iox** [godotengine/escoria#3]
Hi!

First of all, thanks for the amazing work with Escoria. The book is just perfect to get started with point and click games and Godot :)

I'm not sure if this is right place to ask. I'm looking for the example assets that are mentioned in the escoria book, specifically in these pages:

https://fr.flossmanuals.net/creating-point-and-click-games-with-escoria/about-the-example-game/
https://fr.flossmanuals.net/creating-point-and-click-games-with-escoria/creat-your-scene/

Any idea of where they can be found?

Thanks,
Ignacio

**Comment by punto-** [comment]
the book assets are in the flossmanuals repo:
https://github.com/flossmanualsfr/escoria

**Comment by akien-mga** [comment]
Nice, I didn't know about it. I added the link to the README: 4f36171
If it's not linked in the manual itself yet, it should probably be added.

Also, maybe the repo could be renamed to `escoria-in-daiza` to make it clearer that it's a full game and not just a fork of escoria?

**Comment by iox** [comment]
Thanks so much, I will add the link to the book myself :)

**Comment by iox** [comment]
Sorry to be a pain: I have realised that in the book two game projects are mentioned:

* an example game called "first quick game"
* another game called Escoria in Daïza to show some cool feature of Escoria and make us this week more fun

Then it says about the "first quick game":

> To start we prepared some files for you :
>  * the assets so that you can follow this section with the same ressources and get at the end something similar
>  * the first quick game complete project done so that you can have a look at the files if necessary

Is that "asset package" available somewhere? If not, that's no problem, all assets can probably be found and extracted from the "Escoria in Daïza" repository. I would just like to correct the book, so future readers are not confused :).

Thanks again!

**Comment by punto-** [comment]
I don't remember.. someone might know in the issue tracker for that
repository..

**Comment by iox** [comment]
Ok, I'll ask there, thanks!
