### ISSUE TITLE
Multiple Talking Emotions

### ISSUE THREAD

**Issue by lavaduderDev** [godotengine/escoria#30]
I've been using set_state for my emotions, but every time my character uses the default "talk" animation. There are work arounds for this (like using set_state every time a character speaks/stops speaking.), but no default way to have multiple talk emotions.

Will you add the ability for multiple talk animations?

**Comment by punto-** [comment]
Is this on the player character, or on a character that uses the "item.gd"
script? On an item, you can change the name of the talk animation on the
item, using the state animation. It's the "talk_animation" property on the
item script.

**Comment by lavaduderDev** [comment]
Sorry for the long wait. This is for both the player and item.

Okay what I mean by multiple emotions.
I have one character, 
He has a default animation and default tallking animation. 
I also have a angry animation, and a angry talking animation.
I want to be able to interchange the default & angry talking animations in esc script.
That way when the character is done being angry. He will look normal.

When you say talk_animation property, are you talking about the script variable "talk_animation", because I can only set it to ONE talking animation at a time.

**Comment by fleskesvor** [comment]
This should be solved by #147. You can add a second `AnimationPlayer`, "angry", with your angry sprites and use `set_state player angry` to make the player angry. Change back using eg. `set_state player animation`.
