### ISSUE TITLE
Player does not walk to object on pick up

### ISSUE THREAD

**Issue by StraToN** [godotengine/escoria#324]
When using the "pick up button" (in case of 9-verbs UI) on the bottle object in room09, the player does not walk to it, so he won't pick it up either.

**Comment by dploeger** [comment]
I updated the issue description and labels/milestones, but I don't really understand what you mean. Do you mean the bottle with "statue"? What I can reproduce is, that the "pick up" verb just doesn't work with the bottle. Right-Clicking strangely works (although "Pick up" is the default verb). The character moves there in any case, though.

**Comment by StraToN** [comment]
Correct, the "pick up" verb button in 9-verbs UI won't work on the bottle indeed. I rephrazed the issue a bit, hopefully it makes it a bit clearer.
