### ISSUE TITLE
Speech keys and enhancements to dialog lines and dialog choices (speech, translations)

### ISSUE THREAD

**Issue by StraToN** [godotengine/escoria#336]
In recent discussions, we thought about removing speech keys, to use the line text as a key directly.

However we remarked that speech keys were actually use as file names for voice speech sound files in previous Escoria. Using the dialog line as key would not work there, so the speech key remains the better tradeoff here,  allowing both translations of speech lines and voiced speeches to share the key.

This invalidates #325 issue.

For the reminder, these speech keys are defined as in this command:
`say mark key_mark_0001:"Greetings, stranger."`

- [x] Add speech keys to dialog `say` ESC command 
- [x] Add speech keys to dialog options to allow
- [x] Ensure speech keys are optional, since some gamedevs won't bother translating or use voice speech
- [x] Force the avatar id to use the character global_id

**Comment by dploeger** [comment]
I've ticked the last item as in my fix for #345 I moved to having avatar to refer to a scene file instead of any id.
