### ISSUE TITLE
Missing files and directories after 3.0 update

### ISSUE THREAD

**Issue by fleskesvor** [godotengine/escoria#36]
Since the 3.0 update, the project only contains the files which were previously under the device/ directory. This would be a good thing, in my opinion, since the previous structure was a bit confusing to use as a base for a new project, except some useful files are missing now too. Compare the 2.1 and 3.0 directory structure:

2.1:

    ├── device
    │   ├── game
    │   ├── globals
    │   ├── scenes
    │   │   └── test
    │   │       └── player
    │   ├── templates
    │   └── ui
    ├── doc 
    ├── tools
    └── translations

3.0:

    ├── game
    ├── globals
    ├── scenes
    │   └── test
    │       └── player
    ├── templates
    └── ui

Most notably, the README.md and LICENSE.md files and the doc/ and translations/ directories are missing. The tools/ directory is also missing, but I never actually used anything from there, so I'm not sure what they were used for.

**Comment by StraToN** [comment]
My fault. I'll fix this asap.
