### ISSUE TITLE
Esc files must have the same name as the item's global_id

### ISSUE THREAD

**Issue by skhello27** [godotengine/escoria#37]
GODOT 2.1.4 stable, Windows 8.1

[ tutorial ](https://fr.flossmanuals.net/creating-point-and-click-games-with-escoria/creat-actions/
) -- Points from 6 to 12

`Global Id` of my 2DNode is `cat`. Name of scene is cat.tscn
I have four files with same content.

When I set `Events Path` value to `cat.esc` I have two lines of dialog.
When I set `Events Path` value to `cat1.esc` I have two lines of dialog.
When I set `Events Path` value to `old_man.esc` I have ONLY first line of dialog.
When I set `Events Path` value to `кириллица.esc` I have ONLY first line of dialog.

**Comment by JuanNeedsToApologize** [comment]
Not a high priority at all. Juan told me on reddit, reported and voting to close.

**Comment by JuanNeedsToApologize** [comment]
@reduz

**Comment by StraToN** [comment]
Sorry for the very long time response. I'll try to reproduce this problem first so we can determine whether this is a real bug or a misuse at some point.

**Comment by fleskesvor** [comment]
I'm not able to reproduce this issue using https://github.com/flossmanualsfr/escoria/tree/2.1.4.

* I have created changed the contents of `old_man.esc` to:

        :talk
        say cat "Hello young panda."
        say cat "Don't worry, you'll succeed."
        set_global introduced true
        stop

    and copied the file to `cat.esc`, `cat1.esc` and `кириллица.esc`.
* I have changed the name of the `old_man` node to "cat" and also set its global_id to "cat".
* I load the scene, using the four different files as the "Event Paths" value, one after the other.

I see both lines of dialogue printed every time.

@skhello27: If you make your project available on GitHub, I'd be happy to take a look, as I'm not able to retrace the steps required to trigger the described behavior.

**Comment by punto-** [comment]
Do you set the property after loading the scene? maybe that's the problem,
the path has to be set when _ready() is called, that's where the esc is
loaded

**Comment by StraToN** [comment]
@skhello27 Is your problem fixed?

**Comment by mjtorn** [comment]
I tested this with a node with events and no global_id. It worked, I never even considered having a global_id. When I set global_id to something completely different from both the file name and the node name, the events still worked.

Can this issue be closed from clobbering the list?
