### ISSUE TITLE
cyrillic symbols in esc files

### ISSUE THREAD

**Issue by skhello27** [godotengine/escoria#40]
I want to use cyrillic symbols in esc files but when I run scene I can not see them.

**Comment by fleskesvor** [comment]
Have you checked if the font you're using supports Cyrillic symbols?

**Comment by skhello27** [comment]
How and where I can do that? Is where link to documentation on how to use fonts in GE?

**Comment by fleskesvor** [comment]
I'm not sure if it's documented anywhere, but the way to change is mostly the same for regular dialogues, which use `RichTextLabel`s and branching dialogues, which use `Label`s. You have to edit the dialogue scenes, which are `ui/dialog_default.tscn` and `ui/dd_default.tscn`, unless you've made custom dialogues. On the first, you want to edit the "Custom Fonts, Normal Font" property of the `text` node, and on the latter, you want to edit the "Custom Fonts, Font" property of the `label` node.

If you're using a dynamic font, like .ttf or .otf, you want to first set the property to "New DynamicFont" and then click "Edit" on the same property. You then select "Font, Font Data" and load your dynamic font. Once you've done this, given that the font supports the Cyrillic alphabet, you will see these letters in-game.

I've tested this method using both dialogue types and can confirm that this is working as intended. Escoria should perhaps choose a better default font than a system font which doesn't support foreign characters though. It would need to be one under a permissive open-source license though. What do you think, @StraToN?

**Comment by fleskesvor** [comment]
Actually, the procedure is documented in the 3.0 docs:

http://docs.godotengine.org/en/latest/learning/step_by_step/ui_game_user_interface.html#replace-the-label-s-font

**Comment by fleskesvor** [comment]
According to @Calinou, the default font is [Noto Sans in 3.0](https://www.google.com/get/noto/), but it seems only a subset of the font is used, which doesn't include Cyrillic.

**Comment by StraToN** [comment]
@fleskesvor I see no problem with changinf default font to another one, as long as it respects Escoria's original licence, which is MIT.

**Comment by fleskesvor** [comment]
The current font should support a large set of alphabets, including Cyrillic. We should investigate why this isn't working as intended and figure out what needs to be done to simultaneously support multiple languages.
