### ISSUE TITLE
Screen / camera limit issues

### ISSUE THREAD

**Issue by mjtorn** [godotengine/escoria#46]
Hi!

Started looking into remaking my Unity/AC prototype with Escoria and some things have already arisen, some may be accompanied with a pull request if/when I get that far.

Here's one I don't currently feel comfortable pull-requesting.

1)
`global_vm.gd` and `game.gd` make a lot of assumptions about the screen size. My proto was originally drawn for 1280x720 and Escoria is making it somewhat non-trivial to use this.

I was puzzled because I did configure this in `ProjectSettings` _as the documentation tells to_, but there seems to be a strong tendency to assume full-hd resolution. This is made all the more awkward by the fact I have a 4k setup at the office, and I certainly don't want a test window that big!

I'm pretty sure the correct solution would be to consult `ProjectSettings` first and only then the OS!

2)
The documentation could also point out how camera limits work. It may be obvious - at least in retrospect - but upper-left is (0, 0) and as my first scene (background) is 2060x720, the settings should probably be

```
x = 780
y = 0
w = 1280
h = 720
```

Currently the camera-limit part is vague enough to easily miss altogether!

I'm not entirely done with this yet, the stuff I get in my hard-coded 1280x720 window is not correct, maybe partly because...

3)
Godot3 renamed `pos` to `position`. You should be able to fix this faster than I can make a PR, so let's see who gets around to it first ;) But I changed some of these here and let's see where it goes.

(But I'll submit this now so I won't forget to do so, will update later if required)

Thanks!

**Comment by mjtorn** [comment]
I won't be getting the camera limits going today, so I'll ask: should the camera limits essentially follow the limits of the background or should they be like the viewport to the scene or both of the above?

This is made a bit more problematic because the camera does not currently follow the player. Does this need the ESC script in place? Because I didn't get that far yet.

Also noted that `camera.set_limit(...)` is not documented for Godot 3 anymore, but the editor doesn't complain either, so I suppose a fix for this would include setting all the `limit_` attributes one by one.

**Comment by mjtorn** [comment]
Somewhat related to this, what does the ProjectSettings Use Custom Camera do?

I get slightly better results if I turn it on, but this is not documented (afaict) anywhere and I feel very lost right now, guessing about the code and settings.

**Comment by mjtorn** [comment]
I'm attaching screenshots of what it looks like when the camera is off.

The only changes:

  * `global_vm.gd` has the size hard-coded to 1280x720 because ProjectSettings is not honored
  * `game.gd` uses `position` instead of `pos` (still with the old `camera.set_limit(...)` calls)

![proto 01 camera-limits](https://user-images.githubusercontent.com/78427/36026206-b6cf7a3c-0d9e-11e8-8b09-bd4094931b72.png)
![proto 02 no-camera-limits](https://user-images.githubusercontent.com/78427/36026207-b7129ef2-0d9e-11e8-94ae-0e9658bbbe71.png)

I would very much like to understand why the camera is off and not following the player character. The character can be moved, though!

If I enable "Use Custom Camera", I get the camera on the player, but the cropping is way off and the character is near impossible to move to the right.

![proto 03 custom-camera](https://user-images.githubusercontent.com/78427/36026380-6a8f2540-0d9f-11e8-91d9-95cfdf867e3c.png)

**Comment by fleskesvor** [comment]
Camera position and screen resolution is actually something I've discussed a bit with a friend regarding a hobby project we're tinkering with every now and then, but for now we've just decided to ignore the issue. This does appear to be something of a pain point for Escoria though, but since I have no real game dev experience, I'm not sure how this should work ideally.

I think another problem is that the menu template isn't nearly good good enough, and should include examples of how to manage screen resolution (and write to ProjectSettings), as well as managing save games, since these are functionalities all adventure games need.

If we then assume that the player is able to change this from in-game, Escoria should pick resolutions from ProjectSettings if set; and otherwise revert to actual screen resolution.

I'm also thinking that the camera should follow player when they get close to the edge of the viewport, but otherwise stay in place, as I think that's the normal behavior in such games.

**Comment by mjtorn** [comment]
I'd have to fire up Unity/AC to remind myself of how exactly it was done there, but you could define the limits of the camera and some kind of elasticity for how strictly the camera follows the player. This seems like something that should be done.

Changing resolutions is a grand idea, and maybe I should try to give up on this resolution thing and just run with Full HD (but I'm sure I still need to override the size because `OS` reports 4k) for a while. I chose this crappier resolution because of the screen I had at the time and the fact I don't draw.

Another implication of changing resolutions is different aspect ratios when building for Android/iOS. I did find some tutorial mentioning some of the implications there, but I don't know how to apply it and I don't believe I should care just yet.

But for me for now any 16:9 scaling would be more than adequate.

**Comment by fleskesvor** [comment]
I think the case might be that the functionality just hasn't been implemented yet. I'm not familiar enough with Escoria to say for sure though. Would it be possible for you to share the code for your project, eg. on GitHub? It looks like a better use case for these issues than the current demo scene.

**Comment by mjtorn** [comment]
I'll get back to you on that, just running a bit late now.

I think I'm fine with sharing, but I may have used names from a real project I hope to close and want to censor a bunch of stuff if there are references. This is why I care enough to put some effort into investigating Escoria; if I get to run with a real project, I don't want to be stuck with some of my problems with Unity if I can avoid them! Though I don't want to jump ship to Godot+Escoria either if I experience a lot of issues. Fortunately I have some time for exploration still.

Hopefully you'll get it before I leave work today, because Monday's far away ;)

**Comment by fleskesvor** [comment]
No problem. 🙂  Otherwise, I can just make a similar project myself and see how it behaves.

**Comment by mjtorn** [comment]
@fleskesvor all went faster than expected, and here's a fistful of commits https://github.com/mjtorn/godot-escoria-proto

I made a slight effort to reorder the commits and to squash some, but I don't know if you have to care too much about the individual commits.

**Comment by mjtorn** [comment]
@fleskesvor I added a branch to that repo where I upscaled the graphics, and set the `ProjectSettings` window sizes, but it doesn't work any better :(

It would be interesting to know if this is something I haven't understood about Godot or a legit bug in Escoria...

**Comment by mjtorn** [comment]
So far I've found that if I set `camera` in `game.tscn` to `current`, the player is followed correctly!

This does, however, lead to a bug where the coordinates are seemingly random, as the clicks are sent to the `desk` node (in my prototype). Having `current = false`, the camera is just wherever.

If I drag the `desk` node down the tree, it's not rendered. If I set `Mouse.Filter = Ignore` the clicks go to the background node, but the documentation warns that _"If you use a type that is usually non-clickable (like TextureFrame), remember to uncheck the ignore_mouse property of the node, to enable input on it if necessary."_ I'm guessing I can't interact with the node if I ignore mouse events ;P

I also noticed the camera coordinates are completely off-center. Is this because gdscript is expected to update the position or `current = true` is expected to be set or what?

This is a bit of a mess right now, help is still welcome and I'll keep fighting the good fight for some time more, hoping to drop more info here later.

**Comment by mjtorn** [comment]
![proto 04 1080-current-camera](https://user-images.githubusercontent.com/78427/36135858-3f5a6bec-1096-11e8-97bb-9ad137cea912.png)

Attaching a screen shot of what it looks like in 1080 when I use the current camera setting. Still totally off, I'm afraid :(

**Comment by fleskesvor** [comment]
In that last image, the camera is sort of behaving correctly, I think, since the camera doesn't actually follow the player sprite, but the node it's attached to, which is a small node at the bottom of its feet.

Trying to reposition the camera vertically in `update_camera()` doesn't have any effect, though shifting it horizontally works, so I think there might be some conflict with the framework's notion of what the camera limits are. It's as if the top half of the screen is outside the bounds.

**Comment by mjtorn** [comment]
As said on IRC/#escoria, I can confirm the focus point is the node, but this has no effect on the zoom or the bounds and therefore I can't see if the character looks like he's stepping out of the screen when the "navel node" hits the lower edge of the navigation polygon.

**Comment by mjtorn** [comment]
With the merging of #54, this should work just fine. Therefore I'm closing this issue.

Good job, thank you!
