### ISSUE TITLE
Godot's Asset Library integration

### ISSUE THREAD

**Issue by ghost** [godotengine/escoria#5]
Would it be possible/not very time-consuming to add this framework into Godot's Asset Library? It would give this project greater visibility.

By the way, thank you for doing this project, it's helping me a lot. I'm not much of a coder so I can't contribute with much else, but here's a little icon you can use :)

![escoria-icon](https://cloud.githubusercontent.com/assets/23476557/20435538/c78e0bac-adac-11e6-903d-1491e8a041d0.png)

**Comment by StraToN** [comment]
We will definitely look into this ASAP.

**Comment by mjtorn** [comment]
This stuff is pretty well documented at [Making Plugins](https://godot.readthedocs.io/en/3.0/tutorials/plugins/editor/making_plugins.html).

Spent an hour or a bit more and got a basic layout that adds an Escoria tab in the upper-right tab pane next to Scene and Import.

Only problem is that the button events don't seem to do anything :( :( :(

The development cycle is also a bit slow, as the plugin needs to be inactivated and activated again to reload it, but this should ease out.

There are some further considerations, though:

  * What to do with files and scenes? #113 and #114 touch on this
  * Can we separate the UI elements so they're copied from the addon scene directory (or whatever) and use common scripts from Escoria?
  * What sort of buttons would there be? "Configure" for project setup is obvious, but can we reliably alter the scene structure with "New item"?
  * Should the developer be prompted with questions about `export var` options when adding something new? Should something like `global_id` be a mandatory question always or only when the project is configured to enforce them for translation?

There are probably tons of more questions and without a solid work force to figure this stuff out and implement and reiterate on possibly bad choices, it will take a considerable amount of time to have this as a plugin. Even if the button events worked as easily as the documentation says.

**Comment by StraToN** [comment]
Assets location integration already exists for Escoria 3. We'll add the new version as soon as it's ready. Until then closing this issue. Thanks!
