### ISSUE TITLE
Which version of Godot is currently supported?

### ISSUE THREAD

**Issue by jsena42** [godotengine/escoria#52]
I was searching everywhere and this information wasn't exactly clear. Should I stay with the 2.1.4 or can I use the 3.0? I think this should be in the readme.

**Comment by fleskesvor** [comment]
If you use Godot 3.0, you want master, but there's also a [2.1 brach](https://github.com/godotengine/escoria/tree/2.1) which is compatible with 2.1.4.

**Comment by StraToN** [comment]
Readmes have been updated. Thanks !
