### ISSUE TITLE
Clean out all Escoria's custom ProjectSettings entries 

### ISSUE THREAD

**Issue by StraToN** [godotengine/escoria#53]
And re-create them in a proper Escoria category.

The problem here is that it's hard to determine which ProjectSettings are defined specifically for Escoria and which aren't. This is problematic for Width, Height, Test width, Test Height and such, which makes resolution management less straightforward. 

Some of them may be relics of old Escoria, created when Godot didn't manage resolutions as easy as it does now.

**Comment by mjtorn** [comment]
@StraToN good thing I've been a consultant for at least a third of my life, I have some clue as to how shovel old legacy around ;)

This does feel like something between yak-shaving and bikeshedding, but #54 has some commits.

Now that they've been put under `escoria/` they look horrible and I think I'll procrastinate a bit more on some kind of structure.

**Comment by mjtorn** [comment]
@StraToN is this fine by you now in master so can this issue be closed?

**Comment by fleskesvor** [comment]
Closed by #54.
