### ISSUE TITLE
Document new project structure and suggested workflow

### ISSUE THREAD

**Issue by fleskesvor** [godotengine/escoria#68]
One of the main reasons for the new project structure was to make it easier to keep the framework up to date while developing a game under version control in a sub module. The current documentation is lacking when it comes to basic instructions for setting up a project, and I think we should provide some instructions to help developers get started. This could be a separate markdown document in the `docs/` directory, which we might just link to from the usage section in the README for now.

**Comment by StraToN** [comment]
We should consider using a ReadTheDocs repo similarly to https://docs.godotengine.org .

**Comment by fleskesvor** [comment]
I mean, there's no need to make this overly detailed, as there's already a good tutorial (which needs to be updated soon).

**Comment by StraToN** [comment]
New documentation has been starting with Escoria 4, now in main branch.
To be updated though.
