### ISSUE TITLE
Non latin language

### ISSUE THREAD

**Issue by skang1** [godotengine/escoria#7]
Does this handle non latin languages? Korean or Japanese? I didn't use escoria but because I couldn't write that out in the gdscript editor.

**Comment by punto-** [comment]
The .esc files are read using utf8 I think, and everything is shown in
Labels or RichTextLabels, so if you have the right font it should work..
You shouldn't need to put game content in any of the gdscript files, only
the esc and translation files..

**Comment by StraToN** [comment]
I think we can close this issue.
