### ISSUE TITLE
Coding conventions

### ISSUE THREAD

**Issue by fleskesvor** [godotengine/escoria#81]
As Escoria is starting to get more contributions from more developers, I think it might be a good idea to decide on some coding conventions to make it easier for everyone to understand existing code and write new, high-quality code.

For basic syntax and naming conventions, I think we can use the Python's PEP: https://pep8.org/

In addition to that, I think we need some conventions for how to structure declarations and functions in GDScript files to make them easier to navigate. I propose the following rough draft as a starting point:

```
# Constants in upper case
const PI = 3.14

# Exported variables
export(int) var scale = 1

# Global variables
var has_cookie = true

# Private variables with leading underscore
var _count = 0

# Custom getters and setters

# Global functions/API

# Private/helper functions
func _get_ratio(vector):
    return vector.x / vector.y

# Custom/manually connected signal/event handlers, etc.
func _input(event):
    pass

# Node member functions
func _ready()
   pass
```

Properties/functions should also be alphabetized.

This is a discussion topic, so nothing is set in stone.

**Comment by mjtorn** [comment]
I'd add that use things like `foo.position = bar` instead of `foo.set_position(bar)` because I understood from somewhere that properties are the Godot3 way.

**Comment by mjtorn** [comment]
I think we agreed that `get_node("foo")` is to be replaced with `$"foo"`, using the quotes because gdscript doesn't work if you say `$/root`, so the quotes are there for consistency. Does someone disagree?

**Comment by fleskesvor** [comment]
Yes, I agree with that. :+1:

**Comment by fleskesvor** [comment]
There's a [GDScript style guide](https://docs.godotengine.org/en/stable/getting_started/scripting/gdscript/gdscript_styleguide.html) now, which could be used as a starting point. It doesn't address things like property vs method accessors, or `get_node("some_node")` vs `$"some_node"`, but it seems like a good starting point.

I think we need to do some housecleaning of the current code base before it makes sense to add it to our documentation, and start enforcing it on PRs though.

**Comment by StraToN** [comment]
Official GDScript convention will be respected in Escoria rewrite arriving soon. Thanks!
