### ISSUE TITLE
Easier implementation for Puzzle/Custom scenes

### ISSUE THREAD

**Issue by ghost** [godotengine/escoria#84]
Escoria is nice for Point and Clicks, but some times it faults to deliver on a wider range. Loading in a scene that is outside of Escoria's main code is hard. There is no system in place for custom Godot scenes. 
I'll break this done into 3 reasons/examples of what I am referring to.

1. Puzzles
It's typical for an adventure game to have puzzles. (Infact I'm having a hard time naming one that doesn't include them.) Some are timed based, some involved multiple tools, and others require word play with NPCs. But there is also singular screen (I call them scenes due to Godot's Node system.) puzzles, These do not contain the normal characters, or items, but gadgets and gizmos to toy with. They act like an actual puzzle game. The best examples I have are The Whispered world's Chess puzzle, and Deponia's Crane game.

2. Cutscenes
Full motion video is hard to do on Escoria. Just playing a simple cutscene like that of 'The Curse of Monkey Island' takes a custom script, and some imagination to pull off. a simple scene that loads in would be nice. Or better yet use the FMV to cover up a loading segment.

3. Minigames/hybrid
Like puzzles, Minigames change the gameplay drastically, but are more action focus. Sometimes they can be half of the game. The first thing to come to my mind as an example of 'Sam and Max' Car Chase, and strangely the game's own father, 'The Interactive Adventures of Dog Mendonça & Pizzaboy' Boxing minigame.

Either the system is in place, and is poorly explained, or there is no system, with a dev scrambling through all the code, to achieve what they desire. I partially want there to be 
1. a template for loading in puzzles. 
2. an easy way to load in general custom scenes.
That way Escoria has a wide usage, but does not stray from being scumm-like.

**Comment by fleskesvor** [comment]
Implementation wise, 1 and 3 look very similar, and I'd normally refer to both as minigames, whether they are action focused or not. This shouldn't be hard to achieve currently, as long as you instance your custom framework as a child of the scene node. Then you will be able to change to this scene from a regular scene, but you will have to call functions directly on the `vm` singleton from within your custom scene; typically `set_global` and `change_scene`. I agree that this needs better documentation, and in the long term, there should be an example of implementation.

I'm not sure how to do cutscenes. We have an intro cutscene in The Farrier, but as far as I remember, it's just a custom scene with an AnimatedSprite and logic for skipping dialogue. I will investigate which possibilities are available and update this issue when I know more.

**Comment by mjtorn** [comment]
Number 1) is usually called "logic puzzles", while the others are "inventory puzzles".

@fleskesvor how did that AnimatedSprite thing work? I'm not a super huge fan of FMV cutscenes if they can be avoided, as they often look very different stylistically from the rest of the game. A huge reason for my interest in zooming in on scenes is that "cutscenes" are actually just gameplay. Well, gameplay with maybe the player character's interactions disabled ;)

**Comment by fleskesvor** [comment]
Actually, Cheeseness implemented that intro, and my memory was off. It uses multiple sprites and a script to swap them:

https://github.com/Cheeseness/the-farrier/tree/master/scenes/rooms/intro

There should probably be an easier way to do this using an AnimationPlayer, if a method doesn't already exist.

**Comment by dploeger** [comment]
After a rewrite from scratch, Escoria will be re-released in the coming weeks. Because of this, we're closing this issue, because it relates to the old code. If the issue also regards the rewritten code, please feel free to reopen it.

Thanks
